apiVersion: v1
entries:
  pip-demodam:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-11-05T10:24:05.443284+01:00"
    description: A Helm chart for the Verhuizen PWA of 's-Hertogenbosch
    digest: f818910f2fe6b6db9d7878a1f2b4f942217a22cfbda3c4071ba06e9865950f5e
    name: pip-demodam
    type: application
    urls:
    - pip-demodam-0.1.0.tgz
    version: 0.1.0
generated: "2021-11-05T10:24:05.4422836+01:00"
