apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-03T17:31:14.8875223+01:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: 2c2091d5eacc5738a7500dcfc6161cb73005a7479a1c22078c077e30fcf49d1e
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.2.tgz
    version: 0.1.2
  pip-demodam:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-11-03T17:31:14.8749546+01:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/master/api/helm/
      version: 0.1.2
    description: A Helm chart for the Verhuizen PWA of 's-Hertogenbosch
    digest: 5aa332ec25b36ce048da0ffda7b6f5b427e895b3410bcee8b687a116a6b6e60d
    name: pip-demodam
    type: application
    urls:
    - pip-demodam-0.1.0.tgz
    version: 0.1.0
generated: "2021-11-03T17:31:14.8579002+01:00"
